{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:9002/mail',
	requestHeader: {
		'content-type': 'application/json',
		secret_key: '589d95c4c392f347c4d3c9f9'
	},
	requestBody: {
		title: 'title',
		content: 'content',
		from: {
			name: 'admin',
			email: 'admin@clipvnet.com'
		},
		html: false,
		config_name: 'admin',
		to: ['thanhdt@viosoft.com'],
		cc: ['clipvnet@gmail.com'],
		bcc: [],
		attachments:[
			{
				"name": "config.conf",
				"path": "/attachments/2608a365-8e54-4b26-a3cc-f1da5ffa5b32.conf"
			}
		]
	}
}

{
	des: 'Upload',
	method: 'POST',
	url: 'http://localhost:9002/attachments',
	requestHeader: {
		'content-type': 'multipart/form-data',
		secret_key: '589d95c4c392f347c4d3c9f9'
	},
	requestBody: {
		'file:attachments': 'D:\\config.conf'
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:9002/mail?q={"mail_config.auth.user": "clipvnet@gmail.com"}',
	requestHeader: {
		'content-type': 'multipart/form-data',
		secret_key: '589d95c4c392f347c4d3c9f9'
	}
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9002/mail/ITEM_ID',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		title: '',
		content: '',
		to: [],
		cc: [],
		attachments: [],
		trying_time: 0,
		status: 0
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:9002/mail/589ad3ae61b444426c1ec37d',
	requestHeader: {
		'content-type': 'multipart/form-data',
		secret_key: '589d95c4c392f347c4d3c9f9'
	}
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:9002/mail/58a58401b772c341c088742a',
	requestHeader: {
		'content-type': 'multipart/form-data',
		secret_key: '589d95c4c392f347c4d3c9f9'
	}
}

{
	method: 'GET',
	url: 'http://localhost:9600/project-config?plugin=mail',
	requestHeader: {
		'content-type': 'application/json',
		token: '58997ac77e9a4435508973bf-589980092d24aa1dbc5f97ea-5899a970f16f8a25e46ed04c'
	}
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9600/project/58997ac77e9a4435508973bf',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		plugins: { oauthv2: { single_mode: false, session_expired: 60 }, mail: { trying_time: 3, accounts: { 'admin': { auth: { user: 'clipvnet@gmail.com', pass: 'YnVpdGh1aGE5MA==' }, service: 'gmail' , name: 'Super admin' } } } }
	}
}
"plugins" : { "oauthv2" : { "single_mode" : true, "session_expired" : 1800 }, mail: { trying_time: 3, accounts: { 'admin': { user: 'clipvnet@gmail.com', pass: 'YnVpdGh1aGE5MA==', name: 'Super admin' } } } }


db.project.update({"_id" : ObjectId("58a6db5263e9bd2b3c584066")}, {$set: {"plugins" : { "oauthv2" : { "single_mode" : true, "session_expired" : 1800 }, mail: { trying_time: 3, accounts: { 'admin': { user: 'clipvnet@gmail.com', pass: 'YnVpdGh1aGE5MA==', name: 'Super admin' } } } }}})

db.project.update({"_id" : ObjectId("58a6db5263e9bd2b3c584066")}, {$set: {plugins: { oauthv2: { single_mode: false, session_expired: 60 }, mail: { trying_time: 3, accounts: { 'admin': { auth: { user: 'clipvnet@gmail.com', pass: 'YnVpdGh1aGE5MA==' }, service: 'gmail' , name: 'Super admin' } } } }}})