{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:9002/project',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		name: '',
		status: 0
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:9002/project'
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9002/project/ITEM_ID',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		name: '',
		status: 0
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:9002/project/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:9002/project/ITEM_ID'
}