{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:3000/project',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		name: '',
		status: 0,
		plugins: {
			
		}
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:3000/project'
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:3000/project/58945fa6090247160c39aa45',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		name: '',
		status: 0,
		plugins: {
		}
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:3000/project/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:3000/project/ITEM_ID'
}