{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:3000/project',
	requestHeader: {
		'content-type': 'multipart/form-data'
	},
	requestBody: {
		name: '',
		status: 0,
		plugins: {
			oauthv2: {
				_id: single_mode: 0
				session_expired: 0
			}
		},
		roles: [],
		user: [{
			username: ''
			password: null
		}],
		abc: [{
			username: "thanh"
		}],
		'file:image': ''
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:3000/project'
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:3000/project/ITEM_ID',
	requestHeader: {
		'content-type': 'multipart/form-data'
	},
	requestBody: {
		name: '',
		status: 0,
		plugins: {
			oauthv2: {
				_id: single_mode: 0
				session_expired: 0
			}
		},
		roles: [],
		user: [{
			username: ''
			password: null
		}],
		abc: [{
			username: "thanh"
		}],
		'file:image': ''
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:3000/project/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:3000/project/ITEM_ID'
}