{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:9002/TypeSpendings',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		icon: '',
		name: '',
		oder: 0,
		type: 0,
		parent_id:
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:9002/TypeSpendings'
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9002/TypeSpendings/ITEM_ID',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		icon: '',
		name: '',
		oder: 0,
		type: 0,
		parent_id:
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:9002/TypeSpendings/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:9002/TypeSpendings/ITEM_ID'
}